% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
  11pt,
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{float}
\usepackage{caption}
\usepackage{amsmath}
\captionsetup[table]{position=bottom}
\usepackage{float}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={ST231 Assignment},
  pdfauthor={Pratham Bhargava},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{ST231 Assignment}
\author{Pratham Bhargava}
\date{2026-04-28}

\begin{document}
\maketitle

\section{Question 1}\label{question-1}

\subsection{a.}\label{a.}

The estimated coefficient for \(\log(x)\) is 5.930 to 3.d.p. (*)

The value of this estimate does appear reasonable given the application
context. Firstly, by using the volume of a sphere, the volume of a round
diamond is approximately proportional to \(x^3\). Since the mass of the
diamond is proportional to the volume, we have the mass of a round
diamond is approximately proportional to \(x^3\).

Hence, if we have two round diamonds where diamond A is 10\% heavier
than diamond B then we expect the length of diamond A to be
\((1.10^{\frac{1}{3}} - 1) \times 100 = 3.228\)\% (**) longer than the
length of diamond B to 3.d.p.

By M1, we have \[
  \log(\text{price}) = \beta_0 + \beta_1 \log(x).
\] Changing the subject for price we obtain \[
  \text{price} = \exp(\beta_0) \times x^{\beta_1}.
\] Let \(x_A\) and \(x_B\) be the lengths of diamonds A and B
respectively. Similarly, let \(\text{price}_A\) and \(\text{price}_B\)
be the prices of diamonds A and B respectively.

Then, the \begin{align*}
  \text{percentage difference in price} 
  & = \frac{\text{price}_A - \text{price}_B}{\text{price}_B} \times 100 \\
  & = \left(
        \frac{\exp(\beta_0) \times x_A^{\beta_1}}{\exp(\beta_0) \times x_B^{\beta_1}} - 1
      \right) \times 100 \\
  & = \left(
        \left(
          \frac{x_A}{x_B}
        \right)^{\beta_1} - 1
      \right) \times 100 \\
  & = ((1.10^{\frac{1}{3}})^{5.930} - 1) \times 100 && \text{by (*) and (**)}\\
  & = 20.730\%
\end{align*} to 3.d.p. To the nearest integer, we expect diamond A to be
approximately 21 \% more expensive than diamond B, which aligns with the
information shared by the jeweller.

\subsection{b.}\label{b.}

We consider the model M2 where for \(j = 1, \dots, 607\), \[
  \mathbb{E}(\log(\text{Price}_j)) = \beta_0 + \beta_1 \log(x_j) + \beta_2 \log(y_j) + \beta_3 \log(z_j).
\] Using a similar approach to part (a), we obtain
\(\text{Volume} \propto xyz\). Hence,
\(\text{Price} \propto \text{Weight}^2\) and thus
\(\text{Price} \propto (xyz)^2\). Taking logs on both sides yields
\(\log(\text{Price}) = 2\log(x) + 2\log(y) + 2\log(z)\) therefore we
expect \(\beta_i = 2\) for \(i = 1, 2, 3\).

\subsection{c.}\label{c.}

\begin{verbatim}

Call:
lm(formula = log.price ~ log.x + log.y + log.z, data = dia)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.4187 -0.1173 -0.0137  0.1282  0.3530 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  -1.7674     0.1524 -11.595  < 2e-16 ***
log.x        -0.1621     0.8102  -0.200    0.842    
log.y         4.3858     0.7800   5.623 2.87e-08 ***
log.z         1.7823     0.2544   7.006 6.59e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1579 on 603 degrees of freedom
Multiple R-squared:  0.9535,    Adjusted R-squared:  0.9533 
F-statistic:  4126 on 3 and 603 DF,  p-value: < 2.2e-16
\end{verbatim}

\textbf{Null and alternative hypothesis:} \(H_0: \beta_1 = 0\) versus
\(H_A: \beta_1 \neq 0\).

Firstly, considering a significance level of 5\%, the p-value reported
in the \(\mathrm{Pr}(>|t|)\) column for \(\log(x)\) in the model summary
is \(0.842 > 0.05\). Therefore, there is insufficient evidence to reject
the null hypothesis.

\subsection{d.~}\label{d.}

\begin{verbatim}
Analysis of Variance Table

Response: log.price
           Df  Sum Sq Mean Sq   F value    Pr(>F)    
log.x       1 306.762 306.762 12296.292 < 2.2e-16 ***
log.y       1   0.804   0.804    32.209 2.152e-08 ***
log.z       1   1.224   1.224    49.081 6.587e-12 ***
Residuals 603  15.043   0.025                        
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

The \textbf{null and alternative hypotheses} for \(\log(x)\) in the
sequential ANOVA is \(H_0: \beta_1 = 0\) versus \(H_A: \beta_1 \neq 0\).
We take a significance level of 1\% where the p-value equals
\(\mathrm{P}(>|F|)\). In the \(\mathrm{P}(>|F|)\) column of the output
for \(\log(x)\), the p-value is \(<< 0.01\) hence there is insufficient
evidence to reject the null hypothesis. Note this does not contradict
our conclusion in part (c).

While the sequential ANOVA tests the marginal contribution of
\(\log(x)\) before \(\log(y)\) and \(\log(z)\) are added to the model,
the t-tests in part (c) test if \(\log(x)\) adds an explanatory
influence after \(\log(y)\) and \(\log(z)\) are added to the model.

However, a small discrepancy does arise. As \(x\), \(y\), and \(z\) are
highly correlated, once \(\log(y)\) and \(\log(z)\) are added to the
model \(\log(x)\) contributes little additional information to the
model.

\subsection{e.}\label{e.}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth]{st231_assignment_pratham_bhargava_files/figure-latex/1e-scatterplots-1} 

}

\caption{Pairwise scatterplots for $\log(x)$, $\log(y)$ and $\log(z)$.}\label{fig:1e-scatterplots}
\end{figure}

The large difference between the estimated slope coefficients and the
expected values from part (b) are likely due to multi-collinearity. As
\(x\), \(y\) and \(z\) measure the physical dimensions of the same
diamond, all variables measure similar information causing the slope
coefficients to be unstable. In addition, this may make important
variables seem unimportant which is perhaps a reason behind the
insufficient evidence to reject the null hypothesis for \(\log(x)\) in
parts (b) and (c).

To detect multi-collinearity, we use the Variance Inflation Factor (VIF)
which calculates the amount a variance of a variable has been increased
due to multi-collinearity.

\begin{longtable}[]{@{}rrr@{}}
\caption{VIF values for \(\log(x)\), \(\log(y)\),
\(\log(z)\)}\tabularnewline
\toprule\noalign{}
log(x) & log(y) & log(z) \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
log(x) & log(y) & log(z) \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
229.5697 & 208.493 & 23.08002 \\
\end{longtable}

Usually, we consider a \(\text{VIF} > 10\) large and thus implying
multi-collinearity. From Table 1, we see the VIF for \(\log(x)\),
\(\log(y)\) and \(\log(z)\) are greater than 10, although the VIF for
\(\log(z)\) is considerably smaller, hence implying multi-collinearity
between all three predictors.

Furthermore, Figure 1 confirms these predictors are almost perfectly
correlated explaining why the individual coefficient estimates in M2 are
unstable.

\section{Question 2}\label{question-2}

\subsection{a.}\label{a.-1}

\subsection{b.}\label{b.-1}

\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth]{st231_assignment_pratham_bhargava_files/figure-latex/2b-plot 1-1} 

}

\caption{Scatterplot of the logarithm of the price against the logarithm of the weight with fitted curves of the linear model for good cut diamonds and M3 which take observations from good cut and all cut types respectively.}\label{fig:2b-plot 1}
\end{figure}
\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth]{st231_assignment_pratham_bhargava_files/figure-latex/2b-plot 2-1} 

}

\caption{Scatterplot of the logarithm of the price against the logarithm of the weight with fitted curves of the linear model for very good cut diamonds and M3 which take observations from very good cut and all cut types respectively.}\label{fig:2b-plot 2}
\end{figure}
\begin{figure}[H]

{\centering \includegraphics[width=0.6\linewidth]{st231_assignment_pratham_bhargava_files/figure-latex/2b-plot 3-1} 

}

\caption{Scatterplot of the logarithm of the price against the logarithm of the weight with fitted curves of the linear model for ideal cut diamonds and M3 which take observations from ideal cut and all cut types respectively.}\label{fig:2b-plot 3}
\end{figure}

\subsection{c.~}\label{c.-1}

All three scatterplots show a strong linear relationship between
\(\log(\text{weight})\) and \(\log(\text{price})\) and hence a linear
model is suitable in each case. However, the regression line fitted to
each subset is different from the fitted line for M3, particularly in
Figure 4. From Figure 2, for good cut diamonds, we see that the subset
line lies below the M3 line implying M3 overestimates the price of good
cut diamonds on average. From Figure 3, for very good cut diamonds, the
fitted lines are almost identical implying M3 estimates the price of
very good cut diamonds precisely. Finally, from Figure 4, for ideal cut
diamonds, the subset line is above M3 implying M3 systematically
underestimates the price of ideal cut diamonds.

Noticeably, the slopes of all four lines are approximately equal which
suggests there is little use of adding an interaction between cut and
\(\log(\text{weight})\). However, their intercepts differ significantly
across the cut groups which implies adding cut as a main effect is
useful, since it would account for the vertical shift in price
associated with diamonds of equal weights.

\subsection{d.~}\label{d.-1}

\begin{verbatim}
Analysis of Variance Table

Model 1: log.price ~ log.weight
Model 2: log.price ~ log.weight + cut
Model 3: log.price ~ log.weight + cut + log.weight:cut
  Res.Df    RSS Df Sum of Sq       F    Pr(>F)    
1    605 16.756                                   
2    603 15.526  2   1.23049 23.9468 9.855e-11 ***
3    601 15.441  2   0.08507  1.6556    0.1918    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

Since M3 is nested within \(\text{m}_{\text{cut}}\), which in turn is
nested within \(\text{m}_{\text{inter}}\), we use sequential F-tests via
ANOVA. For adding cut as a main effect, the \textbf{null and alternative
hypotheses} are \[
H_0: \beta_{\text{cut}_1} = \beta_{\text{cut}_2} = 0, \quad \text{versus} \quad H_A: (\beta_{\text{cut}_1}, \beta_{\text{cut}_2}) \neq (0, 0). 
\] Since the p-value is \(<<0.01\), at the 1\% significance level we
reject \(H_0\) and conclude that cut is included in the main effect.
Hence, the cut quality of the diamond is a significant predictor of its
price after accounting for weight.

For adding the interaction, the \textbf{null and alternative hypotheses}
are \[
H_0: \beta_{\text{inter}_1} = \beta_{\text{inter}_2} = 0, \quad \text{versus} \quad H_A: (\beta_{\text{inter}_1}, \beta_{\text{inter}_2}) \neq (0, 0). 
\]

From row three of the \(\text{Pr}(>|t|)\) column in the output, we find
the p-value to be 0.192 \textgreater{} 0.01 (to 3.d.p) there is
insufficient evidence to reject the null hypothesis. Hence, the
interaction between cut and \(\log(\text{weight})\) is not needed which
is consistent with the conclusions made from the scatter plots in part
(c).

\subsection{e.}\label{e.-1}

\begin{verbatim}

Call:
lm(formula = log.price ~ cut/log.weight, data = dia)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.50077 -0.11321 -0.01225  0.13273  0.33827 

Coefficients:
                        Estimate Std. Error t value Pr(>|t|)    
(Intercept)              8.47893    0.01132 749.253  < 2e-16 ***
cutIdeal                 0.10708    0.01648   6.497 1.72e-10 ***
cutVery Good             0.05284    0.01663   3.178  0.00156 ** 
cutGood:log.weight       1.95629    0.03054  64.062  < 2e-16 ***
cutIdeal:log.weight      1.93300    0.03089  62.577  < 2e-16 ***
cutVery Good:log.weight  2.01222    0.03214  62.615  < 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1603 on 601 degrees of freedom
Multiple R-squared:  0.9523,    Adjusted R-squared:  0.9519 
F-statistic:  2401 on 5 and 601 DF,  p-value: < 2.2e-16
\end{verbatim}

The formula \(\text{cut}/\log(\text{weight})\) is the same as
\(\text{cut} + \text{cut}:\log{\text{weight}}\). For each cut group,
this fits a model with a separate intercept and slope.

Firstly, let \(x_{iG}\), \(x_iVG\) and \(x_jI\) as indicator variables
for good, very good and ideal cut groups respectively and
\(j = 1, \dots, 607\). Using ``good cut'' as the baseline group, the
model equation for the \(i^{\text{th}}\) observation is:

\begin{multline}
  \log(\text{price}_i) = c_G + \alpha_{VG} x_{iVG} + \alpha_I x_{iI} + \beta_G \log(\text{weight}_i) x_{iG} + \\ \beta_{VG} \log(\text{weight}_i) x_{iVG} + \beta_{I} \log(\text{weight}_i) x_{iI} + \epsilon_i
\end{multline}

We can interpret the parameters as follows:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \(c_G\) is the intercept of the ``good cut'' diamonds which was our
  baseline group.
\item
  \(\alpha_{VG}\) is the difference between the intercepts of the ``good
  cut'' and ``very good'' cut regression lines.
\item
  \(\alpha_I\) is the difference between the intercepts of the ``good
  cut'' and ``ideal cut'' regression lines.
\item
  \(\beta_G\), \(\beta_{VG}\), \(\beta_I\) are the gradients of
  \(\log(\text{weight})\) for good, very good and ideal cut diamonds
  respectively.
\item
  Finally, \(\epsilon_i\) is the error term for the \(i^{\text{th}}\)
  observation.
\end{enumerate}

Rounded to 3.d.p, the least squares estimates are:
\(\hat{c}_G = 8.479, \hat{\alpha}_{VG} = 0.0528, \hat{\alpha}_I = 0.107, \hat{\beta}_G = 1.956, \hat{\beta}_{VG} = 2.012, \hat{\beta}_I = 1.933\).

\section{Question 3}\label{question-3}

\subsection{a.}\label{a.-2}

\begin{figure}

{\centering \includegraphics[width=0.6\linewidth]{st231_assignment_pratham_bhargava_files/figure-latex/3a-1} 

}

\caption{Residuals versus fitted values in log(USD) from M4 overlaid with a Lowess smoother. Red and black data points represent SI and VSI clarity diamonds respectively.}\label{fig:3a}
\end{figure}

From Figure 5, we notice a clear systematic structure in the data by
clarity group. Observations with Slightly Imperfect (SI) clarity tend to
remain below the zero line while observations with Very Slightly
Imperfect (VSI) clarity tend to remain above the zero line across all
the fitted values. This suggests M4 overestimates the
\(\log(\text{price})\) for SI diamonds and underestimates
\(\log(\text{price})\) for VSI diamonds. Hence, this systematic pattern
strongly suggests adding clarity as a predictor to the model will
improve the model.

\subsection{b.}\label{b.-2}

\begin{verbatim}
Analysis of Variance Table

Model 1: log.price ~ log.weight + cut
Model 2: log.price ~ log.weight + cut + clarity
  Res.Df     RSS Df Sum of Sq      F    Pr(>F)    
1    603 15.5260                                  
2    602  6.0558  1    9.4702 941.41 < 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

As M4 is nested within M5 (obtained by setting
\(\beta_{\text{clarity}} = 0\) in M5), we use a partial F-test.

The model under \(H_0\) is
\(\mathbb{E}[\log(\text{price})] = \beta_0 + \beta_1 \log(\text{weight}) + \beta_{\text{cut}}\),
that is, for M4, clarity has no effect on price beyond weight and cut.
Additionally, the model under \(H_A\) is
\(\mathbb{E}[\log(\text{price})] = \beta_0 + \beta_1 \log(\text{weight}) + \beta_{\text{cut}} + \beta_{\text{clarity}}\),
i.e.~that is, for M5, clarity has a non-zero effect on price.

Now, we find the algebraic expression for the test statistic. Let

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \(D_{M4}\) and \(D_{M5}\) be the residual sums of squares of M4 and M5
  respectively,
\item
  \(q\) be the number of additional parameters added when moving from M4
  to M5,
\item
  \(n\) is the number of observations, and
\item
  \(p\) is the total number of parameters in M5.
\end{enumerate}

Then, we have:

\[
  F = \frac{\frac{D_{M4} - D_{M5}}{q}}{\frac{D_{M5}}{n - p}}.
\]

Here, we have \(n = 607\). As clarity has two levels, SI and VSI, a
single indicator variable suffices hence \(q = 1\).

M5 has \(p = 5\) parameters (intercept, \(\log(\text{weight})\), two cut
dummies and finally one clarity dummy). Therefore, under \(H_0\), the
test statistic therefore follows an \(F_{(1,\, 602)}\) distribution.
Now, using the residual sums of squares from the ANOVA output, we obtain
the following, rounding \(F_{\text{obs}}\) to 1.d.p:

\[
F_{\text{obs}} = \frac{\frac{15.526 - 6.056}{1}}{\frac{6.056}{602}} = \frac{9.47}{0.01006} \approx 941.4
\]

Since the p-value is less than 0.01, at the 1\% significance level we
therefore reject the null hypothesis and conclude that clarity is a
statistically significant predictor of the price of the diamonds (even
after accounting for weight and cut).

In the context of this application, the diamond's clarity grade provides
important information regarding the sale price. Hence, a jeweller
looking to predict prices accurately should include clarity in the
model.

\subsection{c.~}\label{c.-2}

Yes. In this case, the partial F-test could be replaced by a two-sided
t-test since \(q = 1\). Clarity is a binary variable with two levels,
that is SI and VSI, thus only one coefficient is being tested.

When the F-statistic has one degree of freedom in the numerator, the
identity \(F = t^2\) holds exactly. This implies the partial F-test and
the two-sided t-test are equivalent and hence will give the same
conclusion.

\end{document}
